# Generated by Django 3.1.5 on 2021-01-05 15:35

from django.db import migrations, models
import src.posts.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UUID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at date')),
                ('title', models.CharField(max_length=120, verbose_name='Заголовок')),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('img', models.ImageField(blank=True, null=True, upload_to=src.posts.models.get_img_path, verbose_name='Фото')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Пост',
                'verbose_name_plural': 'Посты',
                'ordering': ('-created_at',),
            },
        ),
    ]
